### ISSUE TITLE
Prisma client: incorrect TS types for nullable field

### ISSUE THREAD

**Issue by dodas** [prisma/prisma1#3774] opened 2018-12-27 02:18 UTC
Hey guys.
I just noticed that generated TS types for `SomeTypeUpdateInput` doesn't allow `null` for fields that are nullable.
E.g.:
datamodel.graphql:
```graphql
type User {
  id: ID! @unique
  nickname: String
}
```

Trying to update `nickname` to null:
```js
prisma.updateUser({
  where: { id: 'abcdef' },
  data: { nickname: null },
});
```
Executing this code works and have desired outcome, however TypeScript complains:
```
Type 'null' is not assignable to type 'string | undefined'
```

I guess this is bug in generated types?
Thanks.

**Comment by dodas** [comment] 2018-12-28 03:00
I updated both `prisma-client-lib` and global `prisma` cli to latest versions, regenerated client, restarted TS language server in VSCode and still having same issue.
I am not an TS expert, but I guess that when interface says `String` (which is just alias of `string`), it cannot accept `null`.

**Comment by pantharshit00** [comment] 2018-12-28 03:16
No that is not the case. The `?` operator makes it nullable. 

If your project is open source or you can put together a minimal reproduction, please share it.

**Comment by dodas** [comment] 2018-12-28 03:53
Okay, I think I found the reason why I am getting error and you not.
In your `tsconfig.json`, try setting `"strict": true` under `"compilerOptions"` and we should probably have same result.

Note that `?` operator makes an property _optional_, not _nullable_. That is, you can omit it altogether, but not pass `null` or `undefined`.

So I think prisma should generate nullable types as `String | null` to allow strict mode.

**Comment by pantharshit00** [comment] 2018-12-28 04:12
Thanks for the reply!


Main reason here is strictNullCheck and how TS handles null differently when this option is enabled.

You can omit the nickname property for now to achieve the null behavior(ie it will be undefined but we will write it as null in db). We need a bit more discussion internally for inclusion of this change in code generation.

**Comment by dodas** [comment] 2018-12-28 04:32
I just tried ommiting an nullable property and it doesn't update it to null - and honestly, that would be very surprising and dangerous behaviour.
Until this is resolved, I am just using `// @ts-ignore` before line that is passing `null`.

**Comment by pantharshit00** [comment] 2018-12-28 04:54
I though you were using it in `create`.

Indeed this needs a proper resolution now.

**Comment by MathiasKandelborg** [comment] 2019-01-31 08:12
Hi! I've been trying to solve this via graphqlgen. [Here's the issue on that repo](https://github.com/prisma/graphqlgen/issues/417)

> At this point the issue becomes about Prisma, not graphqlgen. Correct me if I am wrong but I believe the issue you are facing is that the Prisma lib param types will not accept `undefined`.
> 
> There are two possible fixes the prisma team can do:
> 
> 1. use GraphQL default feature, e.g.:
>    ```graphql
>    input PostWhereInput {
>      AND: [PostWhereInput!] = null
>    ```
> 2. change their prisma lib to accept `undefined`

**Comment by ellipticaldoor** [comment] 2019-01-31 10:42
> Hi! I've been trying to solve this via graphqlgen. [Here's the issue on that repo](https://github.com/prisma/graphqlgen/issues/417)
> 
> > At this point the issue becomes about Prisma, not graphqlgen. Correct me if I am wrong but I believe the issue you are facing is that the Prisma lib param types will not accept `undefined`.
> > There are two possible fixes the prisma team can do:
> > 
> > 1. use GraphQL default feature, e.g.:
> >    ```graphql
> >    input PostWhereInput {
> >      AND: [PostWhereInput!] = null
> >    ```
> > 2. change their prisma lib to accept `undefined`

The problem is not in the types, the problem is apollo server can accept null as undefined for the input of the resolver.

So if your datamodel doesn't allows null for a field you have to convert your null  from your apollo server input into undefined so you don't get a runtime error.

``` typescript
  const user = await prisma.createUser({
    name,
    settings: {
      create: {
        newsletter: data.settings.newsletter || undefined,
      },
    },
  });
```

In the example above **data** is coming from the **args** of an apollo resolver, in the schema of the **input** the newsletter field is optional but in the datamodel is required so it can't be null.

So the types are fine and they are preventing you to make a runtime error.

**Comment by ellipticaldoor** [comment] 2019-01-31 10:43
So I think there is not an issue here, the behaviour is fine and there's not an error either in apollo or prisma, but is hard to get why null is not valid.

**Comment by jasonkuhrt** [comment] 2019-01-31 13:36
I was wrong about what the issue is here in the thread over on graphqlgen side. It’s not that the param types of prisma client need to also accept undefined, but rather null.

So I don’t think the current Prisma param types are ok as is, rather I think it should _also_ accept explicit null for fields that are nullable. An important detail for usability.

**Comment by ellipticaldoor** [comment] 2019-01-31 14:10
Yes, maybe a solution could be that prisma treats null as undefined, not sure if that can cause conflicts in other place.

**Comment by jasonkuhrt** [comment] 2019-01-31 14:33
> not sure if that can cause conflicts in other place.

It shouldn't because its input (not output) and it increases what's accepted, not reduces.

Its technically possible that the param types are being extracted for use else where (e.g. `Params<prisma.doThing>`) but I highly doubt it.

**Comment by Weakky** [comment] 2019-02-08 09:52
This is preventing `prisma-client` from being used with any type-safe graphql library when `strict` is enabled, such as `graphqlgen`, `graphql-code-generator`, `nexus` or `nexus-prisma`

**Comment by MathiasKandelborg** [comment] 2019-03-22 15:17
Any progress on this? :smile:

**Comment by LawJolla** [comment] 2019-03-29 19:09
Going back to @dodas original issue, it also prevents proper queries.  e.g. a user with no posts

```
prisma.users({
  where: { id: 'abcdef',  posts: undefined },
  data: { nickname: null },
});
```  

will return all users, users with posts included.

```
prisma.users({
  where: { id: 'abcdef',  posts: null },
  data: { nickname: null },
});
```  

Returns all users without posts, but TS yells "Type null is not assignable to type PostWhereInput | undefined"

**Comment by MathiasKandelborg** [comment] 2019-04-02 07:55
While this is in progress, I've migrated my entire codebase to nexus-prisma and it works fine there. 

So for anyone who'd like to keep their strong typing _and_develop with Prisma and have auto-generation; nexus-prisma is the way to go. Nexus uses another paradigm though (code first), it took me about 2-4 hours to wrap my head around the benefits and way to do things. After that, I haven't looked back.

It's so amazing not having to maintain schema files and have everything written in code.

**Comment by P4sca1** [comment] 2019-04-10 09:57
@MathiasKandelborg I am also using `nexus`, but this issue still exists.

Consider having the following schema:
```ts
export const UserWhereInput = inputObjectType({
  name: 'UserWhereInput',
  definition: t => {
    t.id('id', { required: false })
    t.string('email', { required: false })
  },
})

export const UserQuery = extendType({
  type: 'Query',
  definition: t => {
    t.list.field('users', {
      type: 'User',
      args: {
        where: arg({
          type: 'UserWhereInput',
          required: false,
        }),
      },
      resolve: async (root, args, ctx) => {
        try {
          return await ctx.prisma.users({ where: args.where }) // TS Error here
        } catch (err) {
          throw err
        }
      },
    })
  },
})
```

My custom `UserWhereInput` is not assignable to prismas `UserWhereInput`, because the args generated by `nexus` are `type | string | undefined` whereas the types of `prisma` are only `type | undefined`.

`Type 'null' is not assignable to type 'UserWhereInput | undefined'.ts(2345)`

**Comment by steida** [comment] 2019-04-22 22:51
I believe it's solvable with https://github.com/piotrwitek/utility-types. In my case, a plain Required typed helped me.

**Comment by chrisdrackett** [comment] 2019-04-22 23:10
@steida can you elaborate on how that works?

**Comment by pantharshit00** [comment] 2019-04-29 15:00
This has been fixed with prisma cli version `1.32.0-beta.1` :D

**Comment by NikoMontana** [comment] 2019-07-30 10:59
I dont see this issue as solved. Running on prisma-cli on `1.34.3` with nexus `0.12.0-beta.6` and still have to disable `strict` in `tsconfig.json`

**Comment by pantharshit00** [comment] 2019-07-30 13:37
@NikoMontana Can you please provide us with a reproduction repository?

**Comment by markstreich** [comment] 2019-08-10 11:07
> Can you please provide us with a reproduction repository?

I'm having the same issue as well (I think) here's a reproduction example:

https://github.com/prisma/prisma-examples/compare/master...markstreich:strict_null

<img width="908" alt="Screen Shot 2019-08-10 at 2 03 41 PM" src="https://user-images.githubusercontent.com/1214573/62821076-b2655b00-bb77-11e9-8b47-5aad620f1095.png">

**Comment by kylemh** [comment] 2019-08-21 04:33
Ran into this issue from [this example](https://github.com/prisma/prisma-examples/blob/master/typescript/graphql-apollo-server/tsconfig.json). I was gonna submit a PR to remove the comment, but I can't tell if this is resolved or not...

**Comment by pantharshit00** [comment] 2019-08-23 11:27
cc @divyenduz 

We did fix this issue for the field but it is not fixed for the arguments. We still need to wrap arguments in the `Maybe<T>` type.

![image](https://user-images.githubusercontent.com/22195362/63589532-084df000-c5c7-11e9-9219-92329ff1fac3.png)

**Closed** 2022-09-01 18:52 UTC
Labels: bug/2-confirmed, rfc/0-needs-spec, area/client/ts, kind/bug
